version: "2.2"
services:
    pypubsub:
        build: pypubsub
        network_mode: "host"

    client:
        build: client
        network_mode: "host"
        #command: bash -c "sleep 1 && npm start"
        command: bash -c "sleep 1 && ls && cd js-samples && npm i && npm start"
